# -*- coding: utf-8 -*-
"""NetflixDataset.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Lru4V0erisr5mRM_GgOuN9syHbkpLz25
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('/content/mymoviedb.csv' , lineterminator= '\n')

df.head()

df.info()

df['Genre'].head()

df.isnull().sum()

df.duplicated()

df.duplicated().sum()

df.describe()

df['Release_Date'] = pd.to_datetime(df['Release_Date'])
print(df['Release_Date'].dtypes)

df['Release_Date'] = df['Release_Date'].dt.year
print(df['Release_Date'])

df.head()

cols =['Overview','Original_Language','Poster_Url']
df.drop(cols, axis=1, inplace=True)

df.columns

def categorize_col(df, col, labels):
    edges = [df[col].describe()['min'],
             df[col].describe()['25%'],
             df[col].describe()['50%'],
             df[col].describe()['75%'],
             df[col].describe()['max']]

    df[col] = pd.cut(df[col], edges, labels=labels, duplicates='drop')

    return df

labels = ['not_popular','below_avg', 'average', 'popular']

categorize_col(df ,  'Vote_Average', labels)

df['Vote_Average'].unique()

df.head()

df['Vote_Average'].value_counts()

df.dropna(inplace = True)

df.isna().sum()

df['Genre'] = df['Genre'].apply(lambda x: x.split(', ') if isinstance(x, str) else x)
df = df.explode('Genre').reset_index(drop= True)
df.head

df.head()

df['Genre']  = df['Genre'].astype('category')
df['Genre'].dtypes

df.info()

sns.set_style('whitegrid')

df['Genre'].describe()

sns.catplot(y='Genre', data=df, kind='count', order=df['Genre'].value_counts().index,
            color ='#8E44AD')

plt.title("Genre column distribution")

plt.show()

sns.catplot(y='Vote_Average', data=df, kind='count', order=df['Vote_Average'].value_counts().index,
            color ='#4287f5')

plt.title("Votes Distrinbutio")

plt.show()

df[df['Popularity']==df['Popularity'].min()]

df[df['Popularity']== df['Popularity'].max()]

df['Release_Date'].hist()
plt.title('Release Date')
plt.show()

